import type { Metadata } from 'next'
import {Inter, Libre_Baskerville, Montserrat} from 'next/font/google'
import './globals.scss'
import Header from "@/components/header/Header";

const montserrat = Montserrat({ subsets: ['latin'] })

//dynamic import


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} hero-pattern`}>
         <Header />
      {children}
      </body>
    </html>
  )
}
