name: Deploy Next.js App

#Update CI

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "."
          target: "/home/acreativdesign-keycaps/htdocs/keycaps.acreativdesign.fr"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/acreativdesign-keycaps/htdocs/keycaps.acreativdesign.fr/
            npm install 
            npm run build
            pm2 start npm --name "keycaps" -- run start
            pm2 save
