name: Deploy Next.js App

#Update CI

on:
  push:
    branches:
      - master  # Set to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "."
          target: "/home/association-hrafn-hugsadi/htdocs/www.association-hrafn-hugsadi.fr/Hrafn-hugsadi"

      - name: Restart Application
        uses: appleboy/ssh-action@master
#        env:
#          MAIL_SECRET: ${{ secrets.MAIL_SECRET }}
#          NEXT_PUBLIC_RECAPTCHA_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_KEY }}
#          RECAPTHA_SECRET_KEY: ${{ secrets.RECAPTHA_SECRET_KEY }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/association-hrafn-hugsadi/htdocs/www.association-hrafn-hugsadi.fr/Hrafn-hugsadi
            npm install 
            npm run build
            pm2 restart all
